<?php
namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CustomerTest extends TestCase
{
    use DatabaseTransactions;

    protected mixed $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::first();
    }

    public function test_customers_index_page()
    {
        $this
            ->actingAs($this->user, 'sanctum')
            ->getJson('api/v1/customers')
            ->assertOk();
    }

    public function test_customers_create_function()
    {
        $this->actingAs($this->user, 'sanctum');
        $formData = ['name' => 'Client 1','email'=>'client@test.com'];
        $this->json('POST', url('api/v1/customers/create'), $formData)->assertStatus(200);
    }

    public function test_customer_attach_user_method()
    {
        $this->actingAs($this->user, 'sanctum');
        $formData = ['user_id' => 1];
        $this->json('POST', url('api/v1/customers/1/attach-user'), $formData)->assertStatus(200);
    }
}
