<?php
namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class InvoiceTest extends TestCase
{
    protected mixed $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::first();
    }

    public function test_invoice_create_method()
    {
        $this->actingAs($this->user, 'sanctum');
        $formData = ['start' => '2022-07-01', 'end' => '2022-08-01', 'customer_id' => 1];
        $this->json('POST', url('api/v1/invoices'), $formData)->assertStatus(200);
    }

    public function test_invoice_index_method()
    {
        $this->actingAs($this->user, 'sanctum');
        $this->json('GET', url('api/v1/invoices/1'))->assertStatus(200);
    }
}
