<?php
namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SessionTest extends TestCase
{
    use DatabaseTransactions;

    protected mixed $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::first();
    }

    public function test_session_create_method()
    {
        $this->actingAs($this->user, 'sanctum');
        $formData = ['type' => 'appointment', 'user_id' => 1];
        $this->json('POST', url('api/v1/sessions/create'), $formData)->assertStatus(200);
    }
}
